// Generated by CoffeeScript 2.3.0
var isObject, log, merge;

isObject = require('is-object');

merge = require('cush/utils/merge');

log = require('lodge');

module.exports = function(config) {
  var custom, minify, prod;
  prod = !this.dev;
  config = {
    sourceMap: {
      json: false
    },
    mangle: prod,
    toplevel: prod,
    warnings: prod,
    keep_fnames: this.dev,
    output: {
      beautify: prod,
      semicolons: prod,
      quote_style: prod ? 0 : 3
    },
    compress: {
      unused: prod,
      booleans: prod,
      evaluate: prod,
      switches: prod,
      arguments: prod,
      if_return: prod,
      dead_code: prod,
      join_vars: prod,
      sequences: prod,
      comparisons: prod,
      conditionals: prod,
      drop_debugger: prod,
      loops: false,
      inline: false,
      typeofs: false, // IE10 compat
      properties: false,
      hoist_props: false,
      reduce_vars: false,
      reduce_funcs: false,
      side_effects: false,
      collapse_vars: false,
      global_defs: {
        DEBUG: this.dev,
        ENV: this.target
      }
    }
  };
  if (isObject(custom = this.get('uglify'))) {
    merge(config, custom);
  }
  ({minify} = require('@cush/uglify-js'));
  return this.transform('.js', (asset) => {
    var err, result;
    result = minify(asset.content, config);
    if (err = result.error) {
      throw Object.assign({
        message: err.message,
        stack: err.stack
      }, err);
    }
    result.map.sources[0] = this.relative(asset.path);
    return result;
  });
};
